package io.github.chansan.filebridge.core.error;

/** 可稳定映射到 HTTP 状态码和客户端处理逻辑的业务错误码。 */
public enum FileBridgeErrorCode {
  UNAUTHENTICATED,
  ACCESS_DENIED,
  FILE_NOT_FOUND,
  UPLOAD_NOT_FOUND,
  FILE_TOO_LARGE,
  INVALID_REQUEST,
  IDEMPOTENCY_CONFLICT,
  INVALID_PART,
  UPLOAD_PART_CONFLICT,
  UPLOAD_EXPIRED,
  INVALID_UPLOAD_STATE,
  CHECKSUM_MISMATCH,
  STORAGE_FAILURE,
  DATABASE_FAILURE,
  CAPABILITY_NOT_SUPPORTED,
  CONFIGURATION_ERROR
}
